map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  "" $scheme;
}

map $http_x_forwarded_proto $redirect_to_https {
  default 0;
  "" 1;
  http 1;
}

server {
  listen 80;
  server_name yanfeng.club www.yanfeng.club _;

  root /usr/share/nginx/html;
  index index.html;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location /api/ {
    if ($redirect_to_https) {
      return 301 https://$host$request_uri;
    }

    proxy_pass http://api:3001/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
  }

  location /uploads/ {
    if ($redirect_to_https) {
      return 301 https://$host$request_uri;
    }

    proxy_pass http://api:3001/uploads/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
  }

  location / {
    if ($redirect_to_https) {
      return 301 https://$host$request_uri;
    }

    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 443 ssl;
  http2 on;
  server_name yanfeng.club www.yanfeng.club _;

  ssl_certificate /etc/letsencrypt/live/yanfeng.club/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/yanfeng.club/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/yanfeng.club/chain.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  root /usr/share/nginx/html;
  index index.html;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location /api/ {
    proxy_pass http://api:3001/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
  }

  location /uploads/ {
    proxy_pass http://api:3001/uploads/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
